# -*- coding: utf-8 -*-
"""CreditCard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axvhY7WVmQ4PD0C3HhtZtE6K_naSquA8
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import datatable as dt
import evalml
import seaborn as sns
from sklearn import preprocessing
from category_encoders import TargetEncoder
te = TargetEncoder()

data=pd.read_csv('/content/drive/MyDrive/Colab data/train_s3TEQDk.csv')
data=data.drop(data[data['Credit_Product'].isnull()].index)
data['Risk']=data['Vintage']/data['Age']
data['Poshness']=te.fit_transform(data['Region_Code'],data['Avg_Account_Balance'])


data

data.corr()
sns.heatmap(data.corr())

X=data.drop(['Is_Lead','ID'], axis=1)  
y=data.Is_Lead
X.head()

X_train,X_test,y_train,y_test=evalml.preprocessing.split_data(X,y,problem_type='binary')

X_train.head()

from evalml import AutoMLSearch

automl=AutoMLSearch(X_train=X_train,y_train=y_train,problem_type='binary',max_batches=1,optimize_thresholds=True)

automl.search()

automl.rankings

best_pipeline = automl.best_pipeline

automl.describe_pipeline(automl.rankings.iloc[7]["id"])

scores = best_pipeline.score(X_test, y_test,  objectives=evalml.objectives.get_core_objectives('binary'))
print(scores['AUC'])

automl_auc = AutoMLSearch(X_train=X_train, y_train=y_train,
                           problem_type='binary',
                           objective='auc',
                           additional_objectives=['precision'],                    
                           optimize_thresholds=True)
automl_auc.search()

best_pipeline.feature_importance